/* =========================================================
   QUINDIOFLIX - DDL BASE ORACLE XE
   Autor: Diseño propuesto para caso de negocio
   Convenciones:
   - PK numéricas con IDENTITY
   - Nombres en singular
   - Restricciones nombradas
   - ON DELETE CASCADE solo en tablas claramente dependientes
   ========================================================= */

------------------------------------------------------------
-- LIMPIEZA OPCIONAL
------------------------------------------------------------
-- Ejecutar solo si deseas recrear el esquema desde cero.
-- DROP TABLE reporte_contenido CASCADE CONSTRAINTS;
-- DROP TABLE calificacion_contenido CASCADE CONSTRAINTS;
-- DROP TABLE favorito_perfil CASCADE CONSTRAINTS;
-- DROP TABLE reproduccion CASCADE CONSTRAINTS;
-- DROP TABLE episodio CASCADE CONSTRAINTS;
-- DROP TABLE temporada CASCADE CONSTRAINTS;
-- DROP TABLE contenido_relacionado CASCADE CONSTRAINTS;
-- DROP TABLE contenido_genero CASCADE CONSTRAINTS;
-- DROP TABLE contenido CASCADE CONSTRAINTS;
-- DROP TABLE genero CASCADE CONSTRAINTS;
-- DROP TABLE pago_suscripcion CASCADE CONSTRAINTS;
-- DROP TABLE perfil CASCADE CONSTRAINTS;
-- DROP TABLE usuario_rol CASCADE CONSTRAINTS;
-- DROP TABLE rol CASCADE CONSTRAINTS;
-- DROP TABLE usuario CASCADE CONSTRAINTS;
-- DROP TABLE plan_suscripcion CASCADE CONSTRAINTS;
-- DROP TABLE empleado CASCADE CONSTRAINTS;
-- DROP TABLE departamento CASCADE CONSTRAINTS;

------------------------------------------------------------
-- 1. ESTRUCTURA ORGANIZACIONAL
------------------------------------------------------------

CREATE TABLE departamento (
    id_departamento        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre                 VARCHAR2(50 CHAR) NOT NULL,
    descripcion            VARCHAR2(250 CHAR),
    id_jefe                NUMBER,
    fecha_creacion         DATE DEFAULT SYSDATE NOT NULL,
    activo                 CHAR(1 CHAR) DEFAULT 'S' NOT NULL,

    CONSTRAINT pk_departamento PRIMARY KEY (id_departamento),
    CONSTRAINT uq_departamento_nombre UNIQUE (nombre),
    CONSTRAINT ck_departamento_activo CHECK (activo IN ('S','N'))
);

CREATE TABLE empleado (
    id_empleado            NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_departamento        NUMBER NOT NULL,
    id_supervisor          NUMBER,
    nombre                 VARCHAR2(80 CHAR) NOT NULL,
    apellido               VARCHAR2(80 CHAR) NOT NULL,
    email                  VARCHAR2(150 CHAR) NOT NULL,
    telefono               VARCHAR2(20 CHAR),
    cargo                  VARCHAR2(80 CHAR) NOT NULL,
    fecha_contratacion     DATE DEFAULT SYSDATE NOT NULL,
    salario                NUMBER(12,2),
    activo                 CHAR(1 CHAR) DEFAULT 'S' NOT NULL,

    CONSTRAINT pk_empleado PRIMARY KEY (id_empleado),
    CONSTRAINT uq_empleado_email UNIQUE (email),
    CONSTRAINT ck_empleado_salario CHECK (salario IS NULL OR salario >= 0),
    CONSTRAINT ck_empleado_activo CHECK (activo IN ('S','N')),
    CONSTRAINT ck_empleado_supervisor_self CHECK (
        id_supervisor IS NULL OR id_supervisor <> id_empleado
    ),
    CONSTRAINT fk_empleado_departamento
        FOREIGN KEY (id_departamento)
        REFERENCES departamento(id_departamento),
    CONSTRAINT fk_empleado_supervisor
        FOREIGN KEY (id_supervisor)
        REFERENCES empleado(id_empleado)
);

ALTER TABLE departamento
    ADD CONSTRAINT fk_departamento_jefe
    FOREIGN KEY (id_jefe)
    REFERENCES empleado(id_empleado);

------------------------------------------------------------
-- 2. PLANES, USUARIOS Y ROLES
------------------------------------------------------------

CREATE TABLE plan_suscripcion (
    id_plan                NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre                 VARCHAR2(30 CHAR) NOT NULL,
    precio_mensual         NUMBER(10,2) NOT NULL,
    pantallas_simultaneas  NUMBER(2) NOT NULL,
    calidad_video          VARCHAR2(10 CHAR) NOT NULL,
    max_perfiles           NUMBER(2) NOT NULL,
    activo                 CHAR(1 CHAR) DEFAULT 'S' NOT NULL,

    CONSTRAINT pk_plan_suscripcion PRIMARY KEY (id_plan),
    CONSTRAINT uq_plan_nombre UNIQUE (nombre),
    CONSTRAINT ck_plan_precio CHECK (precio_mensual > 0),
    CONSTRAINT ck_plan_pantallas CHECK (pantallas_simultaneas > 0),
    CONSTRAINT ck_plan_perfiles CHECK (max_perfiles > 0),
    CONSTRAINT ck_plan_calidad CHECK (calidad_video IN ('SD','HD','4K')),
    CONSTRAINT ck_plan_activo CHECK (activo IN ('S','N'))
);

CREATE TABLE usuario (
    id_usuario                 NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_plan                    NUMBER NOT NULL,
    id_usuario_referidor       NUMBER,
    nombre                     VARCHAR2(80 CHAR) NOT NULL,
    apellido                   VARCHAR2(80 CHAR) NOT NULL,
    email                      VARCHAR2(150 CHAR) NOT NULL,
    telefono                   VARCHAR2(20 CHAR),
    fecha_nacimiento           DATE NOT NULL,
    ciudad_residencia          VARCHAR2(80 CHAR) NOT NULL,
    fecha_registro             DATE DEFAULT SYSDATE NOT NULL,
    fecha_vencimiento_pago     DATE,
    estado_cuenta              VARCHAR2(15 CHAR) DEFAULT 'ACTIVA' NOT NULL,
    referido_activo            CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    descuento_proximo_pago     NUMBER(5,2) DEFAULT 0 NOT NULL,

    CONSTRAINT pk_usuario PRIMARY KEY (id_usuario),
    CONSTRAINT uq_usuario_email UNIQUE (email),
    CONSTRAINT ck_usuario_estado CHECK (
        estado_cuenta IN ('ACTIVA','SUSPENDIDA','DESACTIVADA')
    ),
    CONSTRAINT ck_usuario_referido_activo CHECK (referido_activo IN ('S','N')),
    CONSTRAINT ck_usuario_descuento CHECK (
        descuento_proximo_pago >= 0 AND descuento_proximo_pago <= 100
    ),
    CONSTRAINT ck_usuario_referidor_self CHECK (
        id_usuario_referidor IS NULL OR id_usuario_referidor <> id_usuario
    ),
    CONSTRAINT fk_usuario_plan
        FOREIGN KEY (id_plan)
        REFERENCES plan_suscripcion(id_plan),
    CONSTRAINT fk_usuario_referidor
        FOREIGN KEY (id_usuario_referidor)
        REFERENCES usuario(id_usuario)
);

CREATE TABLE rol (
    id_rol                 NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre                 VARCHAR2(30 CHAR) NOT NULL,
    descripcion            VARCHAR2(200 CHAR),

    CONSTRAINT pk_rol PRIMARY KEY (id_rol),
    CONSTRAINT uq_rol_nombre UNIQUE (nombre)
);

CREATE TABLE usuario_rol (
    id_usuario             NUMBER NOT NULL,
    id_rol                 NUMBER NOT NULL,
    fecha_asignacion       DATE DEFAULT SYSDATE NOT NULL,

    CONSTRAINT pk_usuario_rol PRIMARY KEY (id_usuario, id_rol),
    CONSTRAINT fk_usuario_rol_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario(id_usuario)
        ON DELETE CASCADE,
    CONSTRAINT fk_usuario_rol_rol
        FOREIGN KEY (id_rol)
        REFERENCES rol(id_rol)
);

CREATE TABLE perfil (
    id_perfil              NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_usuario             NUMBER NOT NULL,
    nombre                 VARCHAR2(60 CHAR) NOT NULL,
    avatar_url             VARCHAR2(300 CHAR),
    tipo_perfil            VARCHAR2(10 CHAR) NOT NULL,
    fecha_creacion         DATE DEFAULT SYSDATE NOT NULL,
    activo                 CHAR(1 CHAR) DEFAULT 'S' NOT NULL,

    CONSTRAINT pk_perfil PRIMARY KEY (id_perfil),
    CONSTRAINT uq_perfil_usuario_nombre UNIQUE (id_usuario, nombre),
    CONSTRAINT ck_perfil_tipo CHECK (tipo_perfil IN ('ADULTO','INFANTIL')),
    CONSTRAINT ck_perfil_activo CHECK (activo IN ('S','N')),
    CONSTRAINT fk_perfil_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario(id_usuario)
        ON DELETE CASCADE
);

------------------------------------------------------------
-- 3. CATALOGO DE CONTENIDOS
------------------------------------------------------------

CREATE TABLE genero (
    id_genero              NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre                 VARCHAR2(50 CHAR) NOT NULL,
    descripcion            VARCHAR2(200 CHAR),
    activo                 CHAR(1 CHAR) DEFAULT 'S' NOT NULL,

    CONSTRAINT pk_genero PRIMARY KEY (id_genero),
    CONSTRAINT uq_genero_nombre UNIQUE (nombre),
    CONSTRAINT ck_genero_activo CHECK (activo IN ('S','N'))
);

CREATE TABLE contenido (
    id_contenido           NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_empleado_publica    NUMBER NOT NULL,
    tipo_contenido         VARCHAR2(15 CHAR) NOT NULL,
    titulo                 VARCHAR2(200 CHAR) NOT NULL,
    anio_lanzamiento       NUMBER(4) NOT NULL,
    duracion_minutos       NUMBER(6),
    sinopsis               VARCHAR2(2000 CHAR),
    clasificacion_edad     VARCHAR2(5 CHAR) NOT NULL,
    fecha_agregado         DATE DEFAULT SYSDATE NOT NULL,
    es_original            CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    activo                 CHAR(1 CHAR) DEFAULT 'S' NOT NULL,

    CONSTRAINT pk_contenido PRIMARY KEY (id_contenido),
    CONSTRAINT ck_contenido_tipo CHECK (
        tipo_contenido IN ('PELICULA','SERIE','DOCUMENTAL','MUSICA','PODCAST')
    ),
    CONSTRAINT ck_contenido_anio CHECK (
        anio_lanzamiento BETWEEN 1900 AND 2100
    ),
    CONSTRAINT ck_contenido_duracion CHECK (
        duracion_minutos IS NULL OR duracion_minutos > 0
    ),
    CONSTRAINT ck_contenido_clasificacion CHECK (
        clasificacion_edad IN ('TP','+7','+13','+16','+18')
    ),
    CONSTRAINT ck_contenido_original CHECK (es_original IN ('S','N')),
    CONSTRAINT ck_contenido_activo CHECK (activo IN ('S','N')),
    CONSTRAINT fk_contenido_empleado_publica
        FOREIGN KEY (id_empleado_publica)
        REFERENCES empleado(id_empleado)
);

CREATE TABLE contenido_genero (
    id_contenido           NUMBER NOT NULL,
    id_genero              NUMBER NOT NULL,

    CONSTRAINT pk_contenido_genero PRIMARY KEY (id_contenido, id_genero),
    CONSTRAINT fk_contenido_genero_contenido
        FOREIGN KEY (id_contenido)
        REFERENCES contenido(id_contenido)
        ON DELETE CASCADE,
    CONSTRAINT fk_contenido_genero_genero
        FOREIGN KEY (id_genero)
        REFERENCES genero(id_genero)
);

CREATE TABLE contenido_relacionado (
    id_contenido_origen    NUMBER NOT NULL,
    id_contenido_destino   NUMBER NOT NULL,
    tipo_relacion          VARCHAR2(25 CHAR) NOT NULL,
    descripcion            VARCHAR2(200 CHAR),

    CONSTRAINT pk_contenido_relacionado
        PRIMARY KEY (id_contenido_origen, id_contenido_destino, tipo_relacion),
    CONSTRAINT ck_contenido_rel_self CHECK (
        id_contenido_origen <> id_contenido_destino
    ),
    CONSTRAINT ck_contenido_rel_tipo CHECK (
        tipo_relacion IN ('SECUELA','PRECUELA','REMAKE','SPIN_OFF','VERSION_EXTENDIDA','RELACIONADO')
    ),
    CONSTRAINT fk_cont_rel_origen
        FOREIGN KEY (id_contenido_origen)
        REFERENCES contenido(id_contenido)
        ON DELETE CASCADE,
    CONSTRAINT fk_cont_rel_destino
        FOREIGN KEY (id_contenido_destino)
        REFERENCES contenido(id_contenido)
        ON DELETE CASCADE
);

CREATE TABLE temporada (
    id_temporada           NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_contenido           NUMBER NOT NULL,
    numero_temporada       NUMBER(4) NOT NULL,
    titulo                 VARCHAR2(200 CHAR),
    fecha_estreno          DATE,
    descripcion            VARCHAR2(500 CHAR),

    CONSTRAINT pk_temporada PRIMARY KEY (id_temporada),
    CONSTRAINT uq_temporada_contenido_num UNIQUE (id_contenido, numero_temporada),
    CONSTRAINT ck_temporada_numero CHECK (numero_temporada > 0),
    CONSTRAINT fk_temporada_contenido
        FOREIGN KEY (id_contenido)
        REFERENCES contenido(id_contenido)
        ON DELETE CASCADE
);

CREATE TABLE episodio (
    id_episodio            NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_temporada           NUMBER NOT NULL,
    numero_episodio        NUMBER(4) NOT NULL,
    titulo                 VARCHAR2(200 CHAR) NOT NULL,
    duracion_minutos       NUMBER(6) NOT NULL,
    sinopsis               VARCHAR2(2000 CHAR),
    fecha_publicacion      DATE,

    CONSTRAINT pk_episodio PRIMARY KEY (id_episodio),
    CONSTRAINT uq_episodio_temporada_num UNIQUE (id_temporada, numero_episodio),
    CONSTRAINT ck_episodio_numero CHECK (numero_episodio > 0),
    CONSTRAINT ck_episodio_duracion CHECK (duracion_minutos > 0),
    CONSTRAINT fk_episodio_temporada
        FOREIGN KEY (id_temporada)
        REFERENCES temporada(id_temporada)
        ON DELETE CASCADE
);

------------------------------------------------------------
-- 4. CONSUMO Y PARTICIPACION
------------------------------------------------------------

CREATE TABLE reproduccion (
    id_reproduccion        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_perfil              NUMBER NOT NULL,
    id_contenido           NUMBER NOT NULL,
    id_episodio            NUMBER,
    fecha_hora_inicio      TIMESTAMP NOT NULL,
    fecha_hora_fin         TIMESTAMP,
    dispositivo            VARCHAR2(15 CHAR) NOT NULL,
    porcentaje_avance      NUMBER(5,2) DEFAULT 0 NOT NULL,

    CONSTRAINT pk_reproduccion PRIMARY KEY (id_reproduccion),
    CONSTRAINT ck_reproduccion_fechas CHECK (
        fecha_hora_fin IS NULL OR fecha_hora_fin >= fecha_hora_inicio
    ),
    CONSTRAINT ck_reproduccion_dispositivo CHECK (
        dispositivo IN ('CELULAR','TABLET','TV','COMPUTADOR')
    ),
    CONSTRAINT ck_reproduccion_avance CHECK (
        porcentaje_avance >= 0 AND porcentaje_avance <= 100
    ),
    CONSTRAINT fk_reproduccion_perfil
        FOREIGN KEY (id_perfil)
        REFERENCES perfil(id_perfil)
        ON DELETE CASCADE,
    CONSTRAINT fk_reproduccion_contenido
        FOREIGN KEY (id_contenido)
        REFERENCES contenido(id_contenido),
    CONSTRAINT fk_reproduccion_episodio
        FOREIGN KEY (id_episodio)
        REFERENCES episodio(id_episodio)
);

CREATE TABLE favorito_perfil (
    id_perfil              NUMBER NOT NULL,
    id_contenido           NUMBER NOT NULL,
    fecha_agregado         DATE DEFAULT SYSDATE NOT NULL,

    CONSTRAINT pk_favorito_perfil PRIMARY KEY (id_perfil, id_contenido),
    CONSTRAINT fk_favorito_perfil_perfil
        FOREIGN KEY (id_perfil)
        REFERENCES perfil(id_perfil)
        ON DELETE CASCADE,
    CONSTRAINT fk_favorito_perfil_contenido
        FOREIGN KEY (id_contenido)
        REFERENCES contenido(id_contenido)
        ON DELETE CASCADE
);

CREATE TABLE calificacion_contenido (
    id_calificacion        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_perfil              NUMBER NOT NULL,
    id_contenido           NUMBER NOT NULL,
    estrellas              NUMBER(1) NOT NULL,
    resena                 VARCHAR2(1000 CHAR),
    fecha_calificacion     DATE DEFAULT SYSDATE NOT NULL,

    CONSTRAINT pk_calificacion_contenido PRIMARY KEY (id_calificacion),
    CONSTRAINT uq_calificacion_perfil_contenido UNIQUE (id_perfil, id_contenido),
    CONSTRAINT ck_calificacion_estrellas CHECK (
        estrellas BETWEEN 1 AND 5
    ),
    CONSTRAINT fk_calificacion_perfil
        FOREIGN KEY (id_perfil)
        REFERENCES perfil(id_perfil)
        ON DELETE CASCADE,
    CONSTRAINT fk_calificacion_contenido
        FOREIGN KEY (id_contenido)
        REFERENCES contenido(id_contenido)
        ON DELETE CASCADE
);

CREATE TABLE reporte_contenido (
    id_reporte             NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_usuario_reporta     NUMBER NOT NULL,
    id_contenido           NUMBER NOT NULL,
    id_moderador_usuario   NUMBER,
    motivo                 VARCHAR2(200 CHAR) NOT NULL,
    descripcion            VARCHAR2(1000 CHAR),
    fecha_reporte          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    estado_reporte         VARCHAR2(15 CHAR) DEFAULT 'PENDIENTE' NOT NULL,
    fecha_resolucion       TIMESTAMP,
    observacion_resolucion VARCHAR2(1000 CHAR),

    CONSTRAINT pk_reporte_contenido PRIMARY KEY (id_reporte),
    CONSTRAINT ck_reporte_estado CHECK (
        estado_reporte IN ('PENDIENTE','EN_REVISION','RESUELTO','RECHAZADO')
    ),
    CONSTRAINT ck_reporte_fechas CHECK (
        fecha_resolucion IS NULL OR fecha_resolucion >= fecha_reporte
    ),
    CONSTRAINT fk_reporte_usuario_reporta
        FOREIGN KEY (id_usuario_reporta)
        REFERENCES usuario(id_usuario),
    CONSTRAINT fk_reporte_contenido
        FOREIGN KEY (id_contenido)
        REFERENCES contenido(id_contenido),
    CONSTRAINT fk_reporte_moderador_usuario
        FOREIGN KEY (id_moderador_usuario)
        REFERENCES usuario(id_usuario)
);

------------------------------------------------------------
-- 5. PAGOS Y FACTURACION
------------------------------------------------------------

CREATE TABLE pago_suscripcion (
    id_pago                NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_usuario             NUMBER NOT NULL,
    fecha_pago             TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    periodo_inicio         DATE NOT NULL,
    periodo_fin            DATE NOT NULL,
    monto_base             NUMBER(10,2) NOT NULL,
    porcentaje_descuento   NUMBER(5,2) DEFAULT 0 NOT NULL,
    monto_pagado           NUMBER(10,2) NOT NULL,
    metodo_pago            VARCHAR2(20 CHAR) NOT NULL,
    estado_pago            VARCHAR2(15 CHAR) NOT NULL,
    referencia_transaccion VARCHAR2(100 CHAR),

    CONSTRAINT pk_pago_suscripcion PRIMARY KEY (id_pago),
    CONSTRAINT ck_pago_periodo CHECK (periodo_fin >= periodo_inicio),
    CONSTRAINT ck_pago_montos CHECK (
        monto_base >= 0 AND monto_pagado >= 0
    ),
    CONSTRAINT ck_pago_descuento CHECK (
        porcentaje_descuento >= 0 AND porcentaje_descuento <= 100
    ),
    CONSTRAINT ck_pago_metodo CHECK (
        metodo_pago IN ('TARJETA_CREDITO','TARJETA_DEBITO','PSE','NEQUI','DAVIPLATA')
    ),
    CONSTRAINT ck_pago_estado CHECK (
        estado_pago IN ('EXITOSO','FALLIDO','PENDIENTE','REEMBOLSADO')
    ),
    CONSTRAINT fk_pago_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario(id_usuario)
);

------------------------------------------------------------
-- 6. INDICES OPERATIVOS RECOMENDADOS
------------------------------------------------------------

CREATE INDEX ix_empleado_departamento ON empleado(id_departamento);
CREATE INDEX ix_empleado_supervisor ON empleado(id_supervisor);

CREATE INDEX ix_usuario_plan ON usuario(id_plan);
CREATE INDEX ix_usuario_referidor ON usuario(id_usuario_referidor);
CREATE INDEX ix_usuario_ciudad ON usuario(ciudad_residencia);
CREATE INDEX ix_usuario_estado ON usuario(estado_cuenta);

CREATE INDEX ix_perfil_usuario ON perfil(id_usuario);

CREATE INDEX ix_contenido_tipo ON contenido(tipo_contenido);
CREATE INDEX ix_contenido_clasificacion ON contenido(clasificacion_edad);
CREATE INDEX ix_contenido_publicador ON contenido(id_empleado_publica);
CREATE INDEX ix_contenido_fecha_agregado ON contenido(fecha_agregado);

CREATE INDEX ix_temporada_contenido ON temporada(id_contenido);
CREATE INDEX ix_episodio_temporada ON episodio(id_temporada);

CREATE INDEX ix_reproduccion_perfil ON reproduccion(id_perfil);
CREATE INDEX ix_reproduccion_contenido ON reproduccion(id_contenido);
CREATE INDEX ix_reproduccion_episodio ON reproduccion(id_episodio);
CREATE INDEX ix_reproduccion_inicio ON reproduccion(fecha_hora_inicio);
CREATE INDEX ix_reproduccion_dispositivo ON reproduccion(dispositivo);

CREATE INDEX ix_calificacion_contenido ON calificacion_contenido(id_contenido);

CREATE INDEX ix_reporte_contenido ON reporte_contenido(id_contenido);
CREATE INDEX ix_reporte_usuario ON reporte_contenido(id_usuario_reporta);
CREATE INDEX ix_reporte_moderador ON reporte_contenido(id_moderador_usuario);
CREATE INDEX ix_reporte_estado ON reporte_contenido(estado_reporte);

CREATE INDEX ix_pago_usuario ON pago_suscripcion(id_usuario);
CREATE INDEX ix_pago_fecha ON pago_suscripcion(fecha_pago);
CREATE INDEX ix_pago_estado ON pago_suscripcion(estado_pago);