------------------------------------------------------------
-- AJUSTE DE IDENTIDADES (ejecutar UNA sola vez tras poblar)
------------------------------------------------------------

-- USUARIO: ya ajustado antes a START WITH 31
-- MAX_ID = 30  -> START WITH 31
ALTER TABLE usuario
MODIFY id_usuario GENERATED BY DEFAULT AS IDENTITY (START WITH 31);

-- PERFIL: ya ajustado
-- MAX_ID = 61  -> START WITH 62
ALTER TABLE perfil
MODIFY id_perfil GENERATED BY DEFAULT AS IDENTITY (START WITH 62);

-- PAGO_SUSCRIPCION: ya ajustado
-- MAX_ID = 105 -> START WITH 106
ALTER TABLE pago_suscripcion
MODIFY id_pago GENERATED BY DEFAULT AS IDENTITY (START WITH 106);

-- PLAN_SUSCRIPCION
-- MAX_ID = 3 -> siguiente 4
ALTER TABLE plan_suscripcion
MODIFY id_plan GENERATED BY DEFAULT AS IDENTITY (START WITH 4);

-- GENERO
-- MAX_ID = 10 -> siguiente 11
ALTER TABLE genero
MODIFY id_genero GENERATED BY DEFAULT AS IDENTITY (START WITH 11);

-- CONTENIDO
-- MAX_ID = 40 -> siguiente 41
ALTER TABLE contenido
MODIFY id_contenido GENERATED BY DEFAULT AS IDENTITY (START WITH 41);

-- TEMPORADA
-- MAX_ID = 15 -> siguiente 16
ALTER TABLE temporada
MODIFY id_temporada GENERATED BY DEFAULT AS IDENTITY (START WITH 16);

-- EPISODIO
-- MAX_ID = 50 -> siguiente 51
ALTER TABLE episodio
MODIFY id_episodio GENERATED BY DEFAULT AS IDENTITY (START WITH 51);

-- REPRODUCCION
-- MAX_ID = 304 -> siguiente 305
ALTER TABLE reproduccion
MODIFY id_reproduccion GENERATED BY DEFAULT AS IDENTITY (START WITH 305);

-- CALIFICACION_CONTENIDO
-- MAX_ID = 122 -> siguiente 123
ALTER TABLE calificacion_contenido
MODIFY id_calificacion GENERATED BY DEFAULT AS IDENTITY (START WITH 123);

-- REPORTE_CONTENIDO
-- MAX_ID = 10 -> siguiente 11
ALTER TABLE reporte_contenido
MODIFY id_reporte GENERATED BY DEFAULT AS IDENTITY (START WITH 11);

-- DEPARTAMENTO
-- MAX_ID = 5 -> siguiente 6
ALTER TABLE departamento
MODIFY id_departamento GENERATED BY DEFAULT AS IDENTITY (START WITH 6);

-- EMPLEADO
-- MAX_ID = 12 -> siguiente 13
ALTER TABLE empleado
MODIFY id_empleado GENERATED BY DEFAULT AS IDENTITY (START WITH 13);

-- ROL
-- MAX_ID = 3 -> siguiente 4
ALTER TABLE rol
MODIFY id_rol GENERATED BY DEFAULT AS IDENTITY (START WITH 4);

-- Notas:
-- - CONTENIDO_GENERO, CONTENIDO_RELACIONADO, FAVORITO_PERFIL, USUARIO_ROL
--   usan PK compuesta, no identity numérica, así que no requieren START WITH.
------------------------------------------------------------